import type { TSubscriptionProviderSlug } from "./subscription-provider";

/**
 * Provider-level minimum daemon versions for subscription control-plane UI.
 *
 * Sparse map — providers absent here have no static floor (live only).
 *
 * `unreleased` means the provider's daemon support is in tree but no
 * provider-capable binary has been published yet. The release publisher
 * stamps every `unreleased` entry to
 * `{ state: "since", version: "<this artifact's bare semver>" }` before the
 * protocol source mirror (injected via `stampFiles`) and commits this file
 * with `DAEMON_RELEASE`. Floors are excluded from daemon binary source
 * pathspecs — `--no-compile` may stamp them without rebuilding. Do not invent
 * a version here by hand, and do not bump a `since` floor on later unrelated
 * releases.
 *
 * AUTOGENERATED body by packages/release when a stamp runs — seed new providers
 * with `{ state: "unreleased" }` until their first daemon publish.
 */

export type TSubscriptionDaemonFloor =
  | { readonly state: "unreleased" }
  | { readonly state: "since"; readonly version: string };

export type TSubscriptionDaemonFloors = Readonly<
  Partial<Record<TSubscriptionProviderSlug, TSubscriptionDaemonFloor>>
>;

export const SUBSCRIPTION_DAEMON_FLOORS: TSubscriptionDaemonFloors = {
  muse: { state: "since", version: "2.7.6" },
};
